CONFIG_PM_DEVICE=y
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y
CONFIG_EVENTS=y

# --- Serial console qua J-Link Virtual COM ---
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_MAX_LEVEL=4
CONFIG_LOG_BACKEND_RTT=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n
CONFIG_LOG_BACKEND_UART=y

CONFIG_BT_CTLR_CONN_RSSI=y
CONFIG_THREAD_NAME=y
CONFIG_REBOOT=y
CONFIG_WATCHDOG=y

# --- 2. BỔ SUNG BỘ NHỚ STACK CHO BLE RX VÀ WORKQUEUE ---
CONFIG_BT_RX_STACK_SIZE=2200
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=2048

# --- 3. ĐỒNG BỘ CẤU HÌNH ATT / L2CAP MTU ---
CONFIG_BT_USER_DATA_LEN_UPDATE=y
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_BT_BUF_ACL_TX_SIZE=521
CONFIG_BT_BUF_ACL_RX_SIZE=521
CONFIG_BT_L2CAP_TX_MTU=512
CONFIG_BT_BUF_ACL_TX_COUNT=20
CONFIG_BT_BUF_EVT_RX_COUNT=30
CONFIG_BT_L2CAP_TX_BUF_COUNT=20
CONFIG_BT_ATT_TX_COUNT=20

CONFIG_BT_GATT_CLIENT=y
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_LBS=y
CONFIG_BT_DEVICE_NAME="Nordic_Device"
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=24
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=40
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y
CONFIG_BT_USER_PHY_UPDATE=y